version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - npm ci
      - npm install -g @angular/cli@16.0.2

  build:
    commands:
      - echo "Building Angular project..."
      - ng build --configuration production

  post_build:
    commands:
      - echo "Deploying to S3 bucket..."
      - aws s3 sync dist/foodadda_Client/ s3://foodadda-client --delete
